#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["structlog"]
# ///
"""Generate a complete .env file with secure secrets for n8n Docker Compose."""

import secrets
import string
import sys
from pathlib import Path

import structlog

logger = structlog.get_logger()

CHARSET = string.ascii_letters + string.digits


def gen(n: int = 32) -> str:
    return secrets.token_hex(n)


def gen_alphanumeric(n: int = 24) -> str:
    return "".join(secrets.choice(CHARSET) for _ in range(n))


def build_env() -> str:
    return f"""# =============================================================================
# n8n Docker Compose — Environment Configuration
# =============================================================================
# Generated by generate-secrets.py — re-run to get new secrets.
# =============================================================================

# --- Container Versions ------------------------------------------------------
N8N_VERSION=2.30.7
POSTGRES_VERSION=18.4
REDIS_VERSION=8.8.0-alpine

# --- n8n Host (for OAuth/callbacks) -----------------------------------------
N8N_HOST=localhost
N8N_PORT=5678
N8N_PROTOCOL=http

# --- Timezone ----------------------------------------------------------------
GENERIC_TIMEZONE=UTC
TZ=UTC

# --- PostgreSQL --------------------------------------------------------------
POSTGRES_USER=n8n
POSTGRES_PASSWORD={gen_alphanumeric()}
POSTGRES_DB=n8n

POSTGRES_NON_ROOT_USER=n8n
POSTGRES_NON_ROOT_PASSWORD={gen_alphanumeric()}

# --- Encryption --------------------------------------------------------------
ENCRYPTION_KEY={gen()}
N8N_OTEL_TRACES_SAMPLE_RATE=0.1
N8N_ENDPOINT_HEALTH=health/live
WEBHOOK_URL=http://localhost:5678/

# --- Task Runners ------------------------------------------------------------
RUNNERS_AUTH_TOKEN={gen()}

# --- Redis -------------------------------------------------------------------
REDIS_PASSWORD={gen_alphanumeric()}
REDIS_MAXMEMORY=256mb
REDIS_MAXMEMORY_POLICY=allkeys-lru
QUEUE_BULL_REDIS_PORT=6379
"""


def main() -> None:
    out = Path(__file__).parent / ".env"
    out.write_text(build_env())
    logger.info("env_generated", path=str(out))
    logger.info("review_needed", fields=["N8N_HOST", "WEBHOOK_URL"])


if __name__ == "__main__":
    try:
        main()
    except Exception:
        logger.exception("fatal")
        sys.exit(1)
